sudo: required

language: python
python:
  - '2.7'

install:
  - pip install ansible

#- ansible-galaxy install -r tests/requirements.yml -p tests/roles
before_script:
  - ansible --version
  - ansible-playbook --syntax-check ./tests/test.yml -i ./tests/hosts
